version: '3'

services:
  difftextrewrite:
    build:
      context: ./DiffTextRewrite
      dockerfile: Dockerfile
    image: difftextrewrite
    container_name: difftextrewrite
    restart: unless-stopped
    ports:
      - "59134:59134"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:59134

  diffsite:
    build:
      context: ./DiffSite
      dockerfile: Dockerfile
    image: diffsite
    container_name: diffsite
    restart: unless-stopped
    ports:
      - "50184:50184"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:50184
